### ISSUE TITLE
Git blame does not update state when new branch checked out

### ISSUE THREAD

**Issue by SamuelBailey** [Sertion/vscode-gitblame#153] opened 2023-09-01 10:01 UTC
When using git in the terminal of vscode, and checking out a new branch, containing different commits to the previous branch, the blame information is not updated, and is incorrect for the new branch.

Performing a `git blame` in the terminal shows the correct blame information.

**Comment by Sertion** [comment] 2023-09-01 16:09
Hey SamuelBailey! Thanks for the report.

This is a duplicate of #115.

**Closed by Sertion** 2023-09-01 16:09 UTC
Labels: duplicate
